"""
Multi-round Interview Engine.

This is a NEW engine that sits alongside the existing InterviewEngine
(app/interview_engine.py).  The existing engine is NOT modified —
backward compatibility is fully preserved.

Responsibilities:
    - Create sessions with an InterviewPlan attached
    - Drive round state transitions
    - Delegate question generation and answer evaluation to round executors
    - Retrieve RAG context per round
    - Persist updated session state

IBM Granite is used for all generative rounds via:
    InterviewerAgent → utils/llm.py → IBMWatsonxService → IBM watsonx.ai

The role remains a free-form string throughout.
"""

from __future__ import annotations

import logging
from typing import Optional

from agents.evaluator_agent import EvaluatorAgent
from agents.interviewer_agent import InterviewerAgent
from app.models import InterviewSession, InterviewTurn
from interview.executors import build_executor
from interview.plan import InterviewPlan, InterviewRound, RoundTurn
from interview.planner import InterviewPlanner
from interview.round_types import RoundState, RoundType

logger = logging.getLogger(__name__)


# ── Shared RAG loader (same pattern as existing engine) ───────────────

def _get_rag_engine():
    try:
        from rag.rag_engine import RAGEngine
        from app.config import get_settings
        settings = get_settings()
        return RAGEngine(
            knowledge_directory=settings.rag_documents_dir,
            vector_directory=settings.rag_vector_dir,
        )
    except Exception as exc:
        logger.warning(
            "RAGEngine unavailable (%s). Continuing without RAG context.",
            type(exc).__name__,
        )
        return None


# ── Multi-round session attachment ───────────────────────────────────

def _ensure_plan_agent(session: InterviewSession, round_: InterviewRound) -> tuple:
    """
    Re-attach or create the interviewer/evaluator agents for a round.
    Agents are ephemeral — not serialised to JSON.

    Returns (interviewer_agent, evaluator_agent).
    """
    key = f"_agent_{round_.round_id}"
    if not hasattr(session, key):
        interviewer = InterviewerAgent(
            role           = session.role,
            interview_type = round_.round_type.value,
            difficulty     = round_.difficulty,
        )
        evaluator = EvaluatorAgent(
            role           = session.role,
            interview_type = round_.round_type.value,
        )
        setattr(session, key, (interviewer, evaluator))
    return getattr(session, key)


# ── MultiRoundEngine ──────────────────────────────────────────────────

class MultiRoundEngine:
    """
    Drives a multi-round interview session.

    Completely separate from the existing InterviewEngine.
    Shares RAG loader and agent classes but has independent lifecycle.
    """

    def __init__(self, planner: Optional[InterviewPlanner] = None):
        self._rag     = _get_rag_engine()
        self._planner = planner or InterviewPlanner()

    # ── Session creation ──────────────────────────────────────────────

    def create_session(
        self,
        candidate_name: str,
        role: str,
        experience_level: str,
        interview_type: str = "mixed",
        candidate_context: str = "",
    ) -> InterviewSession:
        """
        Create a new InterviewSession with an attached InterviewPlan.

        The plan is generated by the planner based on the free-form role.
        The session is returned; callers must persist it.
        """
        from uuid import uuid4

        session = InterviewSession(
            session_id      = str(uuid4()),
            candidate_name  = candidate_name,
            role            = role,
            experience_level= experience_level,
            interview_type  = interview_type,
        )

        plan = self._planner.create_plan(
            role             = role,
            experience_level = experience_level,
        )
        session._plan = plan   # ephemeral on session; serialised via plan.to_dict()

        logger.info(
            "Multi-round session created: %s | role=%r | rounds=%d",
            session.session_id, role, plan.total_rounds,
        )
        return session

    # ── Plan attachment (after load from store) ───────────────────────

    def attach_plan(self, session: InterviewSession, plan_dict: dict) -> None:
        """Re-attach a deserialized plan dict to a session (called after DB load)."""
        session._plan = InterviewPlan.from_dict(plan_dict)

    # ── Round navigation ──────────────────────────────────────────────

    def start_next_round(
        self,
        session: InterviewSession,
        candidate_context: str = "",
    ) -> tuple[InterviewRound, RoundTurn]:
        """
        Start the next round and generate its first question.

        Returns (round, first_turn) where first_turn has the question text.
        The turn is NOT yet added to the round — callers must add it after
        the candidate answers.

        Raises:
            ValueError: if no rounds remain or current round is still active.
        """
        plan = self._get_plan(session)
        current = plan.current_round

        # If current round hasn't started yet, start it
        if current is not None and current.state == RoundState.NOT_STARTED:
            current.start()
        elif current is None or current.state not in (
            RoundState.IN_PROGRESS, RoundState.NOT_STARTED
        ):
            # Need to advance
            current = plan.advance_to_next_round()
            if current is None:
                raise ValueError("All rounds are complete. Interview is finished.")
            current.start()

        return current, self._generate_question(session, current, candidate_context)

    def get_current_question(
        self,
        session: InterviewSession,
        candidate_context: str = "",
    ) -> tuple[InterviewRound, RoundTurn]:
        """
        Generate the next question for the current round.

        Returns (round, turn) — the turn is not yet committed.
        """
        plan    = self._get_plan(session)
        current = plan.current_round

        if current is None:
            raise ValueError("No active round. Call start_next_round() first.")
        if not current.is_in_progress:
            raise ValueError(
                f"Round '{current.title}' is not in progress (state: {current.state})."
            )

        return current, self._generate_question(session, current, candidate_context)

    # ── Answer submission ─────────────────────────────────────────────

    def submit_answer(
        self,
        session: InterviewSession,
        round_id: str,
        question: str,
        answer: str,
        candidate_context: str = "",
        selected_option: Optional[str] = None,   # for MCQ
        code_submission: Optional[str] = None,   # for coding (stored, not executed)
        voice_input_mode: str = "text",          # "voice" | "text"  (Prompt 4)
        transcript: Optional[str] = None,        # STT transcript (Prompt 4)
        voice_duration_sec: Optional[float] = None,  # voice duration (Prompt 4)
    ) -> tuple[RoundTurn, bool]:
        """
        Submit an answer for the current question in the given round.

        Returns (evaluated_turn, round_complete) where round_complete is
        True when the round has reached max_turns and been auto-completed.

        Voice answers: when voice_input_mode="voice", the transcript is stored
        on the turn and passed through to the evaluator for STT-aware evaluation.

        Raises:
            ValueError: if answer is empty, round not found, or round not in progress.
        """
        if not (answer or "").strip() and not selected_option and not code_submission:
            raise ValueError("Answer cannot be empty.")

        plan  = self._get_plan(session)
        round_ = self._find_round(plan, round_id)

        if not round_.is_in_progress:
            raise ValueError(
                f"Round '{round_.title}' is not in progress "
                f"(state: {round_.state}). Cannot submit answer."
            )

        # Build the turn with all metadata
        turn                   = RoundTurn(question=question, answer=answer or "")
        turn.selected_option   = selected_option
        turn.code_submission   = code_submission or (answer if round_.round_type == RoundType.CODING else None)
        turn.voice_input_mode  = voice_input_mode or "text"
        turn.transcript        = transcript
        turn.voice_duration_sec= voice_duration_sec

        # Get executor and evaluate
        executor = self._get_executor(session, round_)
        rag_ctx  = self._retrieve_context(session, candidate_context)

        turn = executor.evaluate_answer(
            round_            = round_,
            turn              = turn,
            role              = session.role,
            candidate_context = candidate_context,
            rag_context       = rag_ctx,
        )

        # Add to round
        round_.turns.append(turn)

        # Also add to legacy session.turns for backward-compatible reporting
        session.add_turn(
            question   = question,
            answer     = answer or "",
            evaluation = turn.evaluation,
        )

        # Auto-complete round when max_turns reached
        round_complete = round_.turn_count >= round_.max_turns
        if round_complete:
            round_.evaluation = executor.build_round_evaluation(round_, session.role)
            round_.complete()
            logger.info(
                "Round '%s' completed: score=%.1f",
                round_.title, round_.evaluation.score,
            )

        return turn, round_complete

    def complete_round_manually(
        self,
        session: InterviewSession,
        round_id: str,
    ) -> None:
        """
        Manually complete the current round (e.g. candidate requests early end).
        Builds the round evaluation from turns completed so far.
        """
        plan  = self._get_plan(session)
        round_ = self._find_round(plan, round_id)

        if not round_.is_in_progress:
            raise ValueError(
                f"Round '{round_.title}' is not in progress."
            )

        executor = self._get_executor(session, round_)
        round_.evaluation = executor.build_round_evaluation(round_, session.role)
        round_.complete()

    # ── Final report ──────────────────────────────────────────────────

    def build_final_report(self, session: InterviewSession) -> dict:
        """
        Build the full multi-round performance report.

        Aggregates:
        - per-round scores and evaluations
        - overall score (average of completed rounds)
        - dimension scores from all technical turns
        - strengths, weaknesses, improvement suggestions

        Does NOT fabricate scores for rounds that were not attempted.
        """
        plan = self._get_plan(session)

        round_reports = []
        for r in plan.rounds:
            if r.is_complete and r.evaluation:
                round_reports.append({
                    "round_id":    r.round_id,
                    "round_type":  r.round_type.value,
                    "title":       r.title,
                    "order":       r.order,
                    "score":       r.evaluation.score,
                    "max_score":   r.evaluation.max_score,
                    "turn_count":  r.turn_count,
                    "strengths":   r.evaluation.strengths,
                    "weaknesses":  r.evaluation.weaknesses,
                    "feedback":    r.evaluation.feedback,
                    "improvement_suggestions": r.evaluation.improvement_suggestions,
                    "correct_count":   r.evaluation.correct_count,
                    "total_questions": r.evaluation.total_questions,
                })

        # Round-type scores (only for completed rounds)
        round_scores = plan.round_scores()
        overall      = plan.overall_score()

        # Aggregate from all turns (for backward-compatible dimension reporting)
        all_strengths   = _dedup_list([
            s for r in plan.rounds for t in r.turns
            for s in (t.evaluation.get("strengths") or [])
        ])
        all_weaknesses  = _dedup_list([
            w for r in plan.rounds for t in r.turns
            for w in (t.evaluation.get("weaknesses") or [])
        ])
        all_suggestions = _dedup_list([
            s for r in plan.rounds for t in r.turns
            for s in (t.evaluation.get("improvement_suggestions") or [])
        ])

        return {
            "session_id":           session.session_id,
            "candidate_name":       session.candidate_name,
            "role":                 session.role,
            "experience_level":     session.experience_level,
            "interview_type":       session.interview_type,
            "total_rounds":         plan.total_rounds,
            "completed_rounds":     len(plan.completed_rounds),
            "overall_score":        overall,
            "round_scores":         round_scores,
            "round_reports":        round_reports,
            "strengths":            all_strengths,
            "weaknesses":           all_weaknesses,
            "improvement_suggestions": all_suggestions,
            "plan_complete":        plan.is_complete,
        }

    # ── Internal helpers ──────────────────────────────────────────────

    def _get_plan(self, session: InterviewSession) -> InterviewPlan:
        if not hasattr(session, "_plan"):
            raise RuntimeError(
                "Session has no InterviewPlan. "
                "Call create_session() or attach_plan() first."
            )
        return session._plan

    def _find_round(self, plan: InterviewPlan, round_id: str) -> InterviewRound:
        for r in plan.rounds:
            if r.round_id == round_id:
                return r
        raise ValueError(f"Round '{round_id}' not found in plan.")

    def _generate_question(
        self,
        session: InterviewSession,
        round_: InterviewRound,
        candidate_context: str = "",
    ) -> RoundTurn:
        executor = self._get_executor(session, round_)
        rag_ctx  = self._retrieve_context(session, candidate_context)
        return executor.generate_question(
            round_            = round_,
            role              = session.role,
            candidate_context = candidate_context,
            rag_context       = rag_ctx,
        )

    def _get_executor(self, session: InterviewSession, round_: InterviewRound):
        interviewer, evaluator = _ensure_plan_agent(session, round_)
        return build_executor(
            round_type        = round_.round_type,
            interviewer_agent = interviewer,
            evaluator_agent   = evaluator,
        )

    def _retrieve_context(
        self,
        session: InterviewSession,
        candidate_context: str = "",
    ) -> str:
        if self._rag is None:
            return ""
        try:
            return self._rag.retrieve_context(
                role             = session.role,
                experience_level = session.experience_level,
                interview_type   = session.interview_type,
                candidate_context= candidate_context,
                top_k            = 3,
            )
        except Exception as exc:
            logger.warning("RAG retrieval failed (%s).", type(exc).__name__)
            return ""


def _dedup_list(items: list) -> list:
    seen = set()
    out  = []
    for item in items:
        k = str(item).lower().strip()
        if k not in seen:
            seen.add(k)
            out.append(item)
    return out
